feat(ME-1629): support for aws ec2 connect
borderzero/border0-cli pull request #103
Opened 2023-07-07 14:34 UTC by btoonk

# Description

Support for aws EC2 Connect upstream method
Fixes # ME-1629

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Tested locally

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

2023-07-07 14:57 UTC, adrianosela requested changes
Overall LGTM. Minor changes requested.

2023-07-07 14:57 UTC, adrianosela commented on cmd/root.go
> +	awsEC2AZ                string
s/awsEC2AZ/awsAvailabilityZone/g

AZs arent specific to EC2, also favour more explicit variable name

2023-07-07 14:57 UTC, adrianosela commented on internal/ssh/proxy.go
> +		log.Fatal(err)
Avoid Fatal in favour of propagating error

2023-07-07 15:00 UTC, adrianosela commented on internal/ssh/proxy.go
> +	privateKey, err := rsa.GenerateKey(rand.Reader, 2048)
Key generation and PEM encoding can be moved to a separate reusable function.

2023-07-10 09:40 UTC, btoonk commented on cmd/root.go
> +	awsEC2AZ                string
ack, changed to awAvailabilityZone

2023-07-10 09:40 UTC, btoonk commented on internal/ssh/proxy.go
> +		log.Fatal(err)
changed.

2023-07-10 09:40 UTC, btoonk commented on internal/ssh/proxy.go
> +	privateKey, err := rsa.GenerateKey(rand.Reader, 2048)
for now we leave it here, we can always change this.

2023-07-10 09:40 UTC, btoonk commented on internal/ssh/proxy.go
> +	privateKey, err := rsa.GenerateKey(rand.Reader, 2048)
for now we leave it here, we can always change this.

2023-07-10 13:50 UTC, adrianosela approved these changes

2023-07-10 18:23 UTC, merged