fix(ME-1894): use outer tls connection for connectorAuth and inner tls connection for e2e encryption
borderzero/border0-cli pull request #201
Opened 2023-08-31 19:54 UTC by btoonk

# Description

use outer tls connection for connectorAuth and inner tls connection for e2e encryption.

Fixes # (ME-1894)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Tested locally

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code

2023-08-31 20:10 UTC, atoonk approved these changes

2023-08-31 20:12 UTC, adrianosela commented on cmd/client/tls/tls.go
> +					var conn net.Conn
this change is redundant

2023-08-31 20:14 UTC, adrianosela commented on internal/client/client.go
> +		return conn, nil
inverted logic reads better.

```
connectorConn := tls.Client(conn, tlsConfig)
if err := connectorConn.Handshake(); err != nil {
	return nil, fmt.Errorf("failed to authenticate to connector: %w", err)
}

if !connectorAuthOnly {
    return connectorConn 
}

_, err := conn.Write([]byte("BORDER0-CLIENT-CONNECTOR-AUTHENTICATED"))
if err != nil {
	conn.Close()
	return nil, fmt.Errorf("failed to write to proxy: %w", err)
}

return conn
```

2023-08-31 20:15 UTC, adrianosela requested changes
comments left, but looks good

2023-08-31 20:16 UTC, adrianosela commented on internal/client/client.go
> +		return conn, nil
`connectorAuthOnly` variable name is confusing too

2023-08-31 20:33 UTC, adrianosela approved these changes

2023-09-01 07:47 UTC, btoonk commented on internal/client/client.go
> +		return conn, nil
agree, changed the logic

2023-09-01 07:47 UTC, merged