fix(ME-2080): close command after ssh session is closed
borderzero/border0-cli pull request #237
Opened 2023-09-28 14:04 UTC by btoonk

# Description

close command after ssh session is closed
Fixes # (ME-2080)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Tested locally, with client portal, ssh, sftp and ansible.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code

2023-09-28 16:43 UTC, adrianosela commented on internal/process/setup.go
> +func SetupUserAndGroups(params *Parameters) error {
keep the logger parameter, if you remove it you also have to remove it from setup_windows.go (where we do use it)

2023-09-28 16:44 UTC, adrianosela requested changes
just a small comment -- this won't build for windows when releasing the CLI. Other than that, looks good.

2023-09-30 14:55 UTC, btoonk commented on internal/process/setup.go
> +func SetupUserAndGroups(params *Parameters) error {
I removed it for windows also, this does not work anyway.  This input/output of this function is directly parsed to the sftp client. Not the connector process.

2023-10-03 20:56 UTC, adrianosela approved these changes

2023-10-03 20:57 UTC, adrianosela commented on internal/ssh/server_unix.go
> +		s.Exit(cmd.ProcessState.ExitCode())
maybe run in a defer?

2023-10-03 20:57 UTC, adrianosela commented on internal/ssh/server_unix.go
> +		s.Exit(cmd.ProcessState.ExitCode())
maybe run in a defer?

2023-10-03 21:13 UTC, merged